### ISSUE TITLE
TT1 Review 

### ISSUE THREAD

**Issue by rkwreck** [rkwreck/Rini-Tri-3-Individual#1]
# Total Score: 4.9/5
### Grader: Rachel Lee      

- [ ] Describe Linked Lists, Describe Java Generic T (Notes)

Queue Add and Delete
- [ ]  Comments
- [ ]  Add
- [ ]  Delete

Merge 2 Queues
- [ ]  Comments
- [ ]  Merge
- [ ]  running example

Build Stack and reverse Queue Order
- [ ]  Comments and Tester
- [ ]  Reverse order
- [ ]  Class Definition

Github Page: https://rkwreck.github.io/Rini-Tri-3-Individual/
README: https://github.com/rkwreck/Rini-Tri-3-Individual

**Comment by rachelklee** [comment]
# Total Score: 4.9/5
## Team Score: 0.9/1

## Checks
- [x]  Describe Linked Lists, Describe Java Generic T (Notes)
- Queue Add and Delete
     - [x] Comments
     - [x] Add, running example
     - [x] Implementation of delete
     - [x] Running example
- Merge 2 Queues
     - [x] Comments
     - [x] Implementation of merge
     - [x] running example
- Build Stack and reverse Queue Order 
     - [x] Class definition
     - [x] Class definition
     - [x] Comments and general purpose tester
     - [x] Reverse order test case from queue to stack

Comments:
- Comments in code are very detailed, very helpful when trying to understand code
- All your code runs on the runtime
- Wiki is descriptive, shows learning and understanding
- Code snippets are concise and show only portions of code
- Tech Talk notes shows engagement in class
- Github pages is well organized and shows info on multiple pages
