### ISSUE TITLE
TT2 Review Ticket

### ISSUE THREAD

**Issue by rkwreck** [rkwreck/Rini-Tri-3-Individual#3]
# Total Score: 4.75/5
# Graded by: Flora Y

**Links:**
[Website (GitHub.io Page)](https://rkwreck.github.io/Rini-Tri-3-Individual/)
[READMe](https://github.com/rkwreck/Rini-Tri-3-Individual)

[Code & Runtime](https://rkwreck.github.io/Rini-Tri-3-Individual/My_Code)

- [ ] Github review page that documents key learnings using code snippets
- [ ] Calculator page that shows highlights of work (0.5)
- [ ] Calculator Code with optional extra credit functions, Runtime, with runnable (no input) Test Data, and input option (1.5)

**Comment by florayuan18** [comment]
Total Score: 
Individual Score: 1.75/2

- The Github review page was very neat and informative.  There was a lot of evidence of reflection and code snippets were included.  The code also included comments.
- Each of the code highlights were shown.  There was a reflection for each piece of code that she chose to highlight. (0.5/0.5)
- The calculator code is complete and running.  There are comments that walk us through the code.  She has a no input version where she used a tester, but she does not have an input version (1.25/1.5)
